import type { Metadata } from "next";
import { CommercialFooter, CommercialHeader } from "@/components/commercial-header";
import { crunchbaseScope, mainstreamCompetitors, marketStatusNotes, pricingEvidence, radarCompanies, researchCutoff } from "@/lib/research";

export const metadata: Metadata = { title: "Market Radar — Concord", description: "A dated, evidence-labeled view of Concord's functional competitors, adjacent platforms, and emerging threats." };

export default function IntelligencePage() {
  return <main className="commercial-page"><CommercialHeader active="intelligence"/>
    <section className="intel-hero"><div><p className="commercial-eyebrow">Competitive intelligence · {researchCutoff}</p><h1>Watch the workflow.<br/><em>Not the category label.</em></h1><p className="commercial-lead">A company becomes strategically material when it can move from visibility to repair, then prove the affected identity’s final retrieval behavior.</p></div><aside><span>Current conclusion</span><strong>No direct competitor verified</strong><p>Medium-confidence inference after the documented search scope. This does not prove that no private or stealth capability exists.</p></aside></section>
    <section className="scope-strip"><article><span>18</span><p>Raw public-search candidates</p></article><article><span>14</span><p>Deduplicated candidates</p></article><article><span>12</span><p>Official-source verified</p></article><article><span>6</span><p>Dated watchlist triggers</p></article></section>
    <section className="intel-section"><div className="intel-title"><p className="commercial-eyebrow">Mainstream landscape</p><h2>Partial solutions are already credible.</h2><p>Concord wins only if it closes the entire loop more clearly than bundled search, security, identity, or internal tooling.</p></div><div className="landscape-table"><div className="landscape-head"><span>Company</span><span>Present class</span><span>Material overlap</span><span>Concord boundary</span></div>{mainstreamCompetitors.map((item) => <article key={item.name}><strong>{item.name}</strong><span>{item.classification}</span><p>{item.overlap}</p><p>{item.gap}</p></article>)}</div></section>
    <section className="radar-section"><div className="intel-title"><p className="commercial-eyebrow">Under-the-radar pass</p><h2>Signals worth monitoring.</h2><p>Priority is deliberately separate from present-day capability. Funding, hiring, or positioning alone never creates a “direct competitor.”</p></div><div className="radar-grid">{radarCompanies.map((company) => <article key={company.name} className={`radar-${company.priority.toLowerCase().replaceAll(" ", "-")}`}><header><span>{company.priority}</span><small>{company.verification}</small></header><h3>{company.name}</h3><p>{company.overlap}</p><dl><div><dt>Why it was easy to miss</dt><dd>{company.whyMissed}</dd></div><div><dt>Reclassification trigger</dt><dd>{company.trigger}</dd></div></dl><footer><span>{company.classification}</span><a href={company.url} target="_blank" rel="noreferrer">Official evidence ↗</a></footer></article>)}</div></section>
    <section className="crunchbase-limit"><div><p className="commercial-eyebrow">Crunchbase access</p><h2>{crunchbaseScope.access}</h2></div><div><p>{crunchbaseScope.limitation}</p><strong>Unavailable fields</strong><ul><li>Advanced employee-range and founding-date combinations</li><li>Full investor-portfolio and last-funding filters</li><li>Stealth and undisclosed-funding result counts</li><li>Database-reported company fields behind account access</li></ul><small>Public and primary-source fallback searches were completed. The search is not exhaustive.</small></div></section>
    <section className="evidence-section"><div className="intel-title"><p className="commercial-eyebrow">Commercial evidence</p><h2>The pricing model is a hypothesis with support—not a copied benchmark.</h2></div><div className="evidence-grid">{pricingEvidence.map((item) => <a href={item.url} target="_blank" rel="noreferrer" key={item.company}><span>{item.evidence}</span><h3>{item.company}</h3><strong>{item.model}</strong><p>{item.implication}</p><small>Source accessed {researchCutoff} ↗</small></a>)}</div><div className="market-status-grid">{marketStatusNotes.map((item) => <a href={item.url} target="_blank" rel="noreferrer" key={item.company}><span>{item.evidence}</span><strong>{item.company}</strong><p>{item.status}</p></a>)}</div></section>
    <CommercialFooter/>
  </main>;
}
