from typing import Protocol

class Destination(Protocol):
    """Readback and retrieval are independent of write responses."""
    records: dict[str, dict]
    def write(self, artifact_id: str, record: dict) -> None: ...
    def delete(self, artifact_id: str) -> None: ...
    def read(self, artifact_id: str) -> dict | None: ...
    def retrieve(self, artifact_id: str, identity: str) -> dict | None: ...

class SourceConnector(Protocol):
    def read_object(self, native_id: str) -> dict: ...
    def probe_identity(self, native_id: str, identity: str) -> dict: ...
