"use client";
import { ArrowRight, ArrowUpRight } from "lucide-react";
export default function ProductBrief({ onDemo }: { onDemo: () => void }) {
  return <>
    <section className="brief-hero c-brief-hero"><div><p className="eyebrow">THE PRODUCT HYPOTHESIS</p><h2>Source information changes.<br /><em>Your agents should keep up.</em></h2><p>Concord is building verified data updates for AI agents. When source content, permissions or records change, the goal is to update connected agent data and check the result.</p><button className="primary-button" onClick={onDemo}>Explore the sample <ArrowRight size={17} /></button></div><img src="/assets/concord-coverage-stone-arch.webp" alt="A limestone arch with ferns in warm natural light" width="1672" height="941" /></section>
    <section className="brief-statement"><span className="chapter-number">01 / THE FIRST COMMERCIAL TEST</span><h2>Start with one critical change:<br />who can still retrieve a document?</h2><p>Permission-aware retrieval and synchronization already exist. The question is whether a team still spends repeated engineering time proving that changes reached its own configured AI application.</p><p>Access revocation is the proposed first commercial use case within the broader data-freshness vision. The first customer hypothesis is a B2B SaaS company with a custom RAG stack and an enterprise release or renewal that needs this evidence. The AI or Backend lead uses Concord; the CTO or VP Engineering owns the proposed budget.</p><p className="source-note">Existing alternatives are substantial: <a href="https://learn.microsoft.com/en-us/azure/search/search-indexer-sharepoint-access-control-lists" target="_blank" rel="noreferrer">Azure AI Search ACL synchronization <ArrowUpRight size={13} /></a> and <a href="https://authzed.com/use-cases/ai-retrieval-augmented-generation" target="_blank" rel="noreferrer">AuthZed’s RAG authorization offering <ArrowUpRight size={13} /></a>. Documentation reviewed September 5, 2026. Vendor descriptions have not been benchmarked against Concord.</p></section>
    <section className="brief-mechanism"><div><span className="chapter-number">02 / THE PROPOSED WORKFLOW</span><h2>A defined route.<br /><em>A reviewable result.</em></h2><p>The customer’s existing stack supplies the source authority and enforcement hook.</p></div><div className="mechanism-list">{[{ n: "01", t: "Observe & scope", d: "Record a permission change and identify registered objects on the agreed retrieval route." }, { n: "02", t: "Apply & read back", d: "Use supported destination actions and inspect the resulting state. An acknowledgement alone is not proof." }, { n: "03", t: "Check & preserve", d: "Run authenticated retrieval checks with denied and allowed controls. Keep unknown and failed results visible." }].map(s => <div key={s.n}><span>{s.n}</span><div><h3>{s.t}</h3><p>{s.d}</p></div></div>)}</div></section>
    <section className="c-section c-pilot-scope"><p className="eyebrow">03 / A PAID DESIGN-PARTNER PILOT</p><h2>One source. One destination.<br /><em>One buying decision.</em></h2><p>Proposed scope: six weeks of observation after technical acceptance. Integration time is estimated separately. The price and recurring model require customer validation.</p><div className="c-brief-columns"><div><h3>The customer provides</h3><ul><li>A team that owns ingestion, retrieval and an existing enforcement hook.</li><li>Effective permissions, identity mapping and authorized test accounts.</li><li>A source-to-object registry and visibility into retrieved context IDs.</li><li>Controlled or disabled caches on the tested route.</li></ul></div><div><h3>Together, we measure</h3><ul><li>Time from an observed change to a verified result.</li><li>Denied access and continued allowed access in agreed tests.</li><li>Engineering time versus native tools and existing scripts.</li><li>Installation effort and willingness to renew at a named price.</li></ul></div></div><p className="c-scope-note">No universal discovery, model unlearning or protection of unregistered copies is promised. A missed observation or an uncovered route remains a coverage gap.</p></section>
    <section className="c-section"><p className="eyebrow">04 / WHAT EXISTS TODAY</p><h2>A working local demonstration.<br /><em>A commercial hypothesis to test.</em></h2><p>The Python engine runs synthetic changes, local repairs and identity checks. Live customer integrations, repeatable deployment and willingness to pay remain unproven. BookStack is an early technical reference; the first commercial integration will follow customer evidence.</p><div className="c-actions"><a className="secondary-button" href="/downloads/concord-product-decision.md" download>Read the product decision</a><a className="secondary-button" href="/downloads/concord-architecture.md" download>Read the architecture</a></div></section>
  </>;
}
