"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, ArrowUpRight, Check, ChevronRight, Download, FileCheck2, Leaf, LoaderCircle, LockKeyhole, RotateCcw, ShieldCheck, TriangleAlert } from "lucide-react";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Toaster } from "@/components/ui/sonner";
import { PythonClient, downloadJSON, type Snapshot, type Proof } from "@/lib/concord/client";
import baseline from "@/lib/concord/baseline.json";
import Nav from "./navigation";
import DependencyFlow from "./dependency-flow";
import ProductBrief from "./product-brief";

export type View = "overview" | "review" | "coverage" | "evidence" | "brief";
const titles: Record<View, string> = { overview: "Overview", review: "Change review", coverage: "Coverage", evidence: "Evidence", brief: "Product brief" };
const scenarios = [{ id: "content", label: "Update sample content" }, { id: "permission", label: "Revoke sample access" }, { id: "probe_failure", label: "Verification unavailable" }, { id: "deletion", label: "Delete sample document" }];
const kindLabels: Record<string, string> = { source: "Source fixture", chunk: "Document chunk", index: "Retrieval record", memory: "Memory fixture" };
type ProbeResult = { allowed: boolean; reason: string; artifact_id: string; content?: string };
type Control = { identity: string; artifact_id: string; result: ProbeResult };
type CaseContext = { baseline: Control[]; after?: Control; observed_at: string };
const labelFor = (stage?: string) => ({ contained: "Contained · repair needed", repaired: "Repair applied · check pending", verified: "Sample checks passed", unverified: "Not verified", failed: "Repair failed" }[stage ?? ""] ?? "Ready to explore");
function Badge({ state, children }: { state?: string; children: React.ReactNode }) { return <span className={`c-badge ${state === "verified" ? "c-good" : state === "failed" ? "c-bad" : state === "unverified" ? "c-warn" : ""}`}>{children}</span>; }
function Nature({ compact = false, variant = "overview" }: { compact?: boolean; variant?: "overview" | "review" | "coverage" | "evidence" }) { const artwork = { overview: "living-network", review: "concord-review-stone-ferns", coverage: "concord-coverage-stone-arch", evidence: "concord-evidence-balanced-stones" }[variant]; return <div className={`c-nature ${compact ? "c-nature-small" : ""}`} aria-hidden="true"><img src={`/assets/${artwork}.webp`} alt="" width="1672" height="941" /></div>; }

export default function ConcordWorkspace() {
  const [view, setView] = useState<View>("overview");
  const [snapshot, setSnapshot] = useState<Snapshot>(baseline as unknown as Snapshot);
  const [engineStatus, setEngineStatus] = useState("loading");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [source, setSource] = useState("src-forecast");
  const [scenario, setScenario] = useState("content");
  const [eventId, setEventId] = useState<string | null>(null);
  const [contexts, setContexts] = useState<Record<string, CaseContext>>({});
  const [proofContexts, setProofContexts] = useState<Record<string, CaseContext>>({});
  const [selectedProof, setSelectedProof] = useState<Proof | null>(null);
  const [selectedNode, setSelectedNode] = useState<string | null>(null);
  const [identity, setIdentity] = useState("alex");
  const [probe, setProbe] = useState<ProbeResult | null>(null);
  const [resetOpen, setResetOpen] = useState(false);
  const client = useRef<PythonClient | null>(null);
  useEffect(() => {
    const hash = window.location.hash.slice(1);
    const aliases: Record<string, View> = { lineage: "review", connections: "coverage" };
    if (hash in titles) setView(hash as View); else if (aliases[hash]) setView(aliases[hash]);
    const c = new PythonClient(); client.current = c;
    c.command({ action: "snapshot" }).then(r => { setSnapshot(r.snapshot); setEngineStatus("ready"); }).catch(e => { setError(e.message); setEngineStatus("error"); });
    return () => { c.close(); client.current = null; };
  }, []);
  const navigate = (v: View) => { setView(v); window.history.replaceState(window.history.state, "", `#${v}`); window.scrollTo({ top: 0, behavior: "instant" }); };
  const command = async (payload: Record<string, unknown>) => { if (!client.current) throw new Error("Python runtime unavailable. Reload to retry."); const r = await client.current.command(payload); setSnapshot(r.snapshot); return r.result; };
  const safely = async (action: () => Promise<void>) => { setBusy(true); setError(null); try { await action(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const change = snapshot.events.find(e => e.id === eventId) ?? snapshot.events[0];
  const proof = snapshot.proofs.find(p => p.id === change?.proof_id);
  const context = proof ? proofContexts[proof.id] : change ? contexts[change.id] : undefined;
  const title = (id: string) => snapshot.nodes.find(n => n.id === id)?.title ?? id;
  const locked = busy || engineStatus !== "ready";
  const sourceId = change?.source_id ?? source;
  const branch = snapshot.nodes.filter(n => n.id === sourceId || n.id.endsWith(sourceId.replace("src", "")));
  const start = () => safely(async () => {
    if (snapshot.events.some(e => e.stage !== "verified")) throw new Error("Finish the open change or reset the demo before starting another. Each scenario needs an unaffected control.");
    const target = source.replace("src-", "index-");
    const other = snapshot.nodes.find(n => n.kind === "index" && n.id !== target && n.status === "current" && !n.deleted);
    if (!other) throw new Error("Reset the sample workspace to restore an unaffected control document.");
    const controls: Control[] = [];
    for (const [who, artifact] of [["alex", target], ["jordan", target], ["alex", other.id]]) {
      const result = await command({ action: "probe", artifact_id: artifact, identity: who });
      controls.push({ identity: who, artifact_id: artifact, result });
    }
    if (controls.some(c => !c.result.allowed)) throw new Error("The sample baseline is no longer valid. Reset the demo before starting this scenario.");
    const key = Array.from(crypto.getRandomValues(new Uint8Array(16)), b => b.toString(16).padStart(2, "0")).join("");
    const result = await command({ action: "detect", source_id: source, kind: scenario, identity: "alex", key });
    setContexts(prev => ({ ...prev, [result.id]: { baseline: controls, observed_at: new Date().toISOString() } }));
    setEventId(result.id); navigate("review");
  });
  const repair = () => safely(async () => { if (change) await command({ action: "repair", event_id: change.id }); });
  const verify = () => safely(async () => {
    if (!change) return;
    const record = await command({ action: "verify", event_id: change.id });
    const before = context?.baseline[2];
    if (before) { const result = await command({ action: "probe", artifact_id: before.artifact_id, identity: before.identity }); const frozen = { ...contexts[change.id], after: { ...before, result } }; setProofContexts(prev => ({ ...prev, [record.id]: prev[record.id] ?? frozen })); }
  });
  const reset = () => safely(async () => { await command({ action: "reset" }); setEventId(null); setContexts({}); setProofContexts({}); setSelectedProof(null); setSelectedNode(null); setProbe(null); navigate("overview"); });
  const exportProof = (p: Proof) => downloadJSON(`concord-${p.id}-sample.json`, { artifact_type: "synthetic_demo_evidence", live_integration: false, coverage: "Registered in-memory fixtures in this browser session only", limitations: ["No live source, identity provider, customer endpoint, external cache or enterprise enforcement", "A hash detects changes only against a trusted copy; it is not an external signature", "Checks are point-in-time samples, not a guarantee of all retrieval behavior"], verification_result: p.result === "verified" && proofContexts[p.id]?.after?.result.allowed === true ? "sample_checks_passed" : "not_verified", proof: p, controls: proofContexts[p.id] ?? null });
  const casePass = proof?.result === "verified" && context?.after?.result.allowed === true;
  const unknown = proof?.checks.some(c => c.observed === "unknown");
  const reviewLabel = proof ? casePass ? "Sample checks passed" : unknown ? "Unknown · check unavailable" : "Not verified · inspect results" : labelFor(change?.stage);
  return <SidebarProvider style={{ "--sidebar-width": "238px" } as React.CSSProperties}>
    <Nav view={view} onView={navigate} />
    <div className="main-shell c-workspace">
      <header className="topbar"><div className="breadcrumbs"><SidebarTrigger className="mobile-menu" /><span>Workspace</span><ChevronRight size={14} /><strong>{titles[view]}</strong></div><button className="reset-button" onClick={() => setResetOpen(true)} disabled={locked}><RotateCcw size={15} /><span>Reset demo</span></button></header>
      <div className="c-prototype"><span><Leaf size={14} /> Historical step-by-step lab · Sample data</span><a href="/" className="sync-text-button">Back to automatic workspace</a><span className="c-runtime">{engineStatus === "ready" ? "Python runtime ready" : engineStatus === "loading" ? "Starting Python runtime…" : "Runtime unavailable"}</span></div>
      <main id="main-content" className={`main-content c-main view-${view}`}>
        {error && <div className="c-error" role="alert"><TriangleAlert size={18} /><div><strong>Action could not complete</strong><p>{error}</p></div></div>}
        {view === "overview" && <>
          <section className="c-hero"><Nature /><div className="c-hero-copy"><p className="eyebrow">DATA FRESHNESS FOR AI AGENTS</p><h1>Keep your AI agents’ data<br /><em>up to date.</em></h1><p>When source information changes, Concord updates connected agent data and verifies the result.</p><div className="c-actions"><button className="primary-button" onClick={start} disabled={locked}>{busy ? <LoaderCircle className="animate-spin" size={17} /> : <ArrowRight size={17} />} Run the demo</button><button className="c-text-button" onClick={() => navigate("brief")}>Review pilot scope <ArrowUpRight size={16} /></button></div><small>This demo does not connect to or protect your organization’s systems.</small></div></section>
          <div className="c-metrics">{[[snapshot.counts.sources, "Sample sources"], [snapshot.counts.derivatives, "Registered derivatives"], [snapshot.counts.blocked, "Locally contained"], [snapshot.proofs.length, "Evidence records"]].map(([n, label]) => <div key={label}><span>{n}</span><p>{label}</p></div>)}</div>
          <section className="c-section"><div className="c-section-heading"><div><p className="eyebrow">01 / START WITH ONE CHANGE</p><h2>A small change.<br /><em>A consequence you can inspect.</em></h2></div><p>Alex’s account stays active. Access to one document is removed. Jordan should still be able to retrieve it.</p></div><div className="c-scenario"><div><label htmlFor="sample-source">Sample document</label><select id="sample-source" value={source} onChange={e => setSource(e.target.value)} disabled={locked}>{snapshot.nodes.filter(n => n.kind === "source").map(n => <option key={n.id} value={n.id}>{n.title}</option>)}</select></div><div><label htmlFor="sample-scenario">Scenario</label><select id="sample-scenario" value={scenario} onChange={e => setScenario(e.target.value)} disabled={locked}>{scenarios.map(s => <option key={s.id} value={s.id}>{s.label}</option>)}</select></div><button className="primary-button" onClick={start} disabled={locked}>Run source change <ArrowRight size={16} /></button></div><p className="c-caption">The baseline checks both identities and an unrelated document before the change. Lab scenarios demonstrate the engine; the proposed pilot focuses on access revocation.</p></section>
          <section className="c-section"><div className="c-row-heading"><h2>Recent changes</h2><span>{snapshot.events.length} in this session</span></div>{snapshot.events.length ? <div className="c-change-list">{snapshot.events.map(e => <button key={e.id} onClick={() => { setEventId(e.id); navigate("review"); }}><span className="c-change-icon"><LockKeyhole size={20} /></span><span><strong>{title(e.source_id)}</strong><small>{e.id} · {e.kind.replace("_", " ")} · Alex</small></span><Badge state={e.stage === "verified" && !proofContexts[e.proof_id ?? ""]?.after?.result.allowed ? "unverified" : e.stage}>{e.stage === "verified" && !proofContexts[e.proof_id ?? ""]?.after?.result.allowed ? "Control check needed" : labelFor(e.stage)}</Badge><ChevronRight size={18} /></button>)}</div> : <div className="c-empty-inline"><FileCheck2 size={25} /><p>No changes yet. Run the sample to create your first review.</p></div>}</section>
        </>}
        {view === "review" && <>
          <section className="c-page-title"><div><p className="eyebrow">02 / CHANGE REVIEW</p><h1>Follow the change.<br /><em>Check the consequence.</em></h1><p>Repair and verification are separate steps.</p></div><Nature compact variant="review" /></section>
          {!change ? <Empty onStart={start} disabled={locked} /> : <>
            <div className="c-case-heading"><div><p className="eyebrow">{change.id} · SOURCE REVISION {change.source_revision}</p><h2>{title(change.source_id)}</h2><p>{change.kind === "permission" || change.kind === "probe_failure" ? "Alex’s access to this document was revoked. The sample account remains active." : `Lab scenario: ${change.kind}. This is outside the initial access-revocation pilot.`}</p></div><Badge state={casePass ? "verified" : proof ? "unverified" : change.stage}>{reviewLabel}</Badge></div>
            <ol className="c-steps"><li className="done"><span><Check size={17} /></span><div><strong>Change recorded</strong><small>{change.affected.length} registered derivatives</small></div></li><li className={["repaired", "verified", "unverified"].includes(change.stage) ? "done" : ""}><span>2</span><div><strong>Repair applied</strong><small>Local destination readback follows</small></div></li><li className={casePass ? "done" : ""}><span>3</span><div><strong>Access checked</strong><small>{casePass ? "Sample controls passed" : "Evidence required"}</small></div></li></ol>
            <div className="c-next-action"><div><h3>{casePass ? "The configured sample checks passed." : change.stage === "repaired" ? "The repair is applied. Now verify it." : unknown ? "The verification check was unavailable." : change.stage === "verified" ? "Additional controls were not verified." : "Affected sample retrieval is contained."}</h3><p>{casePass ? "Alex is evaluated against the changed policy. Positive controls check that allowed retrieval still works. This result covers the registered local fixtures only." : unknown ? "Unknown is not a pass. The local engine keeps affected retrieval contained. Reset to compare with the passing scenario." : change.stage === "verified" ? "The engine released its local gate, but the additional control did not pass. This case is not verified. Export the record and reset the demo." : "Containment here is enforced only by the local demo engine. No customer system is connected."}</p></div><div className="c-actions">{!casePass && change.stage !== "verified" && <button className="primary-button" disabled={locked} onClick={change.stage === "repaired" ? verify : repair}>{busy ? <LoaderCircle className="animate-spin" size={17} /> : change.stage === "repaired" ? <ShieldCheck size={17} /> : <ArrowRight size={17} />}{change.stage === "repaired" ? "Verify identity access" : change.stage === "contained" ? "Repair affected data" : "Retry sample repair"}</button>}{proof && <button className="secondary-button" onClick={() => { setSelectedProof(proof); navigate("evidence"); }}>Inspect evidence <ArrowRight size={16} /></button>}</div></div>
            <section className="c-section"><div className="c-row-heading"><h2>What the checks cover</h2><span>Two identities · one unrelated control</span></div><div className="c-controls">{[{ who: "Alex", desc: "Changed document", before: context?.baseline[0], check: proof?.checks.find(c => c.check === "protected_retrieval_probe" && c.identity === "alex" && c.artifact_id?.startsWith("index-")) }, { who: "Jordan", desc: "Same document · allowed control", before: context?.baseline[1], check: proof?.checks.find(c => c.check === "protected_retrieval_probe" && c.identity === "jordan" && c.artifact_id?.startsWith("index-")) }, { who: "Alex", desc: "Unrelated document · allowed control", before: context?.baseline[2], check: context?.after ? { passed: context.after.result.allowed, observed: context.after.result.allowed ? "allow" : "deny" } : undefined }].map((c, i) => <div key={i}><span className="c-person">{c.who[0]}</span><h3>{c.who}</h3><p>{c.desc}</p><dl><div><dt>Before</dt><dd>{c.before?.result.allowed ? "Allowed" : "Not captured"}</dd></div><div><dt>After</dt><dd className={c.check ? c.check.passed ? "c-positive" : "c-negative" : ""}>{c.check ? `${c.check.observed === "allow" ? "Allowed" : "Denied"} · ${c.check.passed ? "as expected" : "unexpected"}` : "Not verified"}</dd></div></dl></div>)}</div></section>
            <details className="c-map"><summary>Inspect the registered dependency map <span>Sample lineage</span></summary><DependencyFlow nodes={branch} affected={change.affected} onSelect={id => { setSelectedNode(id); setProbe(null); }} /><p className="c-caption">The memory node is a fixture, not a connected agent memory service. Unregistered copies are outside this demo’s coverage.</p></details>
          </>}
        </>}
        {view === "coverage" && <>
          <section className="c-page-title"><div><p className="eyebrow">03 / COVERAGE</p><h1>Know the boundary.<br /><em>Then trust the result.</em></h1><p>Connections and coverage must be demonstrated separately.</p></div><Nature compact variant="coverage" /></section>
          <div className="c-coverage-banner"><Leaf size={24} /><div><h2>Local fixtures are running. Live systems are not connected.</h2><p>The Python engine runs in your browser. Nothing on this page grants access to your organization’s data.</p></div></div>
          <section className="c-section"><div className="c-row-heading"><h2>Current demonstration</h2><Badge>Sample data only</Badge></div><div className="c-table-wrap"><table className="c-table"><thead><tr><th>Component</th><th>Status</th><th>Actual coverage</th></tr></thead><tbody>{[["Source authority", "Local fixture", "3 sample documents and explicit Alex / Jordan access lists"], ["BookStack adapter", "Partial prototype", "No live source session or effective-permission integration verified"], ["Destination", "In-memory index", "9 registered derivatives; deterministic local writes and readback"], ["Qdrant adapter", "Partial prototype", "HTTP transport exists; live engine integration is not verified"], ["Identity checks", "Local simulation", "Two sample identities, registered retrieval and positive controls"], ["Caches & agent memory", "Outside live coverage", "One memory fixture per source; no external cache or memory service"], ["Evidence", "Session-local JSON", "Sample checks and hashes; export before resetting or reloading"]].map(row => <tr key={row[0]}>{row.map((v, i) => i === 0 ? <th scope="row" key={i}>{v}</th> : <td key={i}>{v}</td>)}</tr>)}</tbody></table></div></section>
          <section className="c-section c-pilot-scope"><p className="eyebrow">PROPOSED COMMERCIAL PILOT</p><h2>One source. One destination.<br /><em>The application’s real retrieval route.</em></h2><p>Choose the first source with a paying design partner. SharePoint, Confluence and Google Drive are discovery candidates, not shipping connectors.</p><ul><li>Customer-owned ingestion, retriever and an existing enforcement hook.</li><li>Effective source permissions and mapped test identities.</li><li>Registered object IDs from source to destination.</li><li>Every active cache on the tested route is controlled or disabled.</li><li>Authenticated retrieval checks with returned context IDs and allowed controls.</li></ul><button className="secondary-button" onClick={() => navigate("brief")}>Review pilot scope <ArrowRight size={16} /></button></section>
        </>}
        {view === "evidence" && <>
          <section className="c-page-title"><div><p className="eyebrow">04 / EVIDENCE</p><h1>A repair is a step.<br /><em>The check is the evidence.</em></h1><p>Inspect each observation, its identity and the boundary it covers.</p></div><Nature compact variant="evidence" /></section>
          {!snapshot.proofs.length ? <Empty onStart={() => navigate(change ? "review" : "overview")} disabled={false} evidence /> : <><div className="c-evidence-layout"><div className="c-evidence-list" aria-label="Evidence records">{snapshot.proofs.map(p => <button className={(selectedProof?.id ?? snapshot.proofs[0]?.id) === p.id ? "selected" : ""} key={p.id} onClick={() => setSelectedProof(p)}><FileCheck2 size={20} /><span><strong>{p.id}</strong><small>{title(p.source_id)}</small><Badge state={p.result === "verified" && proofContexts[p.id]?.after?.result.allowed ? "verified" : "unverified"}>{p.result === "verified" && proofContexts[p.id]?.after?.result.allowed ? "Sample checks passed" : "Not verified"}</Badge></span></button>)}</div><Evidence proof={selectedProof ?? snapshot.proofs[0]} context={proofContexts[(selectedProof ?? snapshot.proofs[0]).id]} onExport={exportProof} title={title} /></div></>}
          <p className="c-caption">These are point-in-time sample observations. A local hash is not an external signature, a compliance certification or proof that every information copy was checked.</p>
        </>}
        {view === "brief" && <ProductBrief onDemo={() => navigate("overview")} />}
        <footer className="c-footer"><Leaf size={15} /><span>Concord · Verified data updates for AI agents</span><span>Sample workspace · No live integrations</span></footer>
      </main>
    </div>
    <Dialog open={!!selectedNode} onOpenChange={open => { if (!open) setSelectedNode(null); }}><DialogContent className="c-node-dialog"><DialogHeader><DialogTitle>{selectedNode ? title(selectedNode) : "Registered object"}</DialogTitle><DialogDescription>{kindLabels[snapshot.nodes.find(n => n.id === selectedNode)?.kind ?? ""]} · Local fixture</DialogDescription></DialogHeader><p>Only registered derivatives can be queried. This runs through the demo’s local retrieval gate.</p>{snapshot.nodes.find(n => n.id === selectedNode)?.kind !== "source" && <><label htmlFor="probe-identity">Sample identity</label><select id="probe-identity" value={identity} onChange={e => { setIdentity(e.target.value); setProbe(null); }}><option value="alex">Alex</option><option value="jordan">Jordan</option></select><button className="primary-button" disabled={locked} onClick={() => safely(async () => { setProbe(await command({ action: "probe", artifact_id: selectedNode, identity })); })}>Check sample retrieval</button>{probe && <div role="status"><strong>{probe.allowed ? "Allowed" : "Denied"}</strong><p>{probe.reason}</p>{probe.content && <blockquote>{probe.content}</blockquote>}</div>}</>}</DialogContent></Dialog>
    <AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reset this sample workspace?</AlertDialogTitle><AlertDialogDescription>This clears this browser session’s changes and evidence. Export any records you want to keep first.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep working</AlertDialogCancel><AlertDialogAction onClick={reset}>Reset sample data</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Toaster />
  </SidebarProvider>;
}
function Empty({ onStart, disabled, evidence = false }: { onStart: () => void; disabled: boolean; evidence?: boolean }) { return <section className="c-empty"><Leaf size={32} /><h2>{evidence ? "Evidence starts with a check." : "Your first change starts here."}</h2><p>{evidence ? "Run a source change, apply its repair, then verify identity access. Both passing and unavailable checks create a record." : "Explore a document-access change with two sample identities and a controlled local destination."}</p><button className="primary-button" disabled={disabled} onClick={onStart}>{evidence ? "Go to the scenario" : "Run the demo"}<ArrowRight size={16} /></button></section>; }
function Evidence({ proof, context, onExport, title }: { proof: Proof; context?: CaseContext; onExport: (p: Proof) => void; title: (id: string) => string }) {
  const passed = proof.result === "verified" && context?.after?.result.allowed === true;
  return <article className="c-proof"><div className="c-row-heading"><div><p className="eyebrow">{proof.id} · {proof.event_id}</p><h2>{passed ? "Sample checks passed" : proof.checks.some(c => c.observed === "unknown") ? "Unknown · check unavailable" : "Not verified"}</h2></div><button className="secondary-button" onClick={() => onExport(proof)}><Download size={16} /> Export JSON</button></div><p>{title(proof.source_id)} · Revision {proof.source_revision}</p><dl className="c-proof-meta"><div><dt>Coverage</dt><dd>Registered local fixtures</dd></div><div><dt>Observed</dt><dd>{new Date(proof.created_at * 1000).toISOString()}</dd></div><div><dt>Live integration</dt><dd>None</dd></div><div><dt>Baseline</dt><dd>{context?.baseline.every(c => c.result.allowed) ? "Both identities + unrelated control allowed" : "Not available"}</dd></div></dl><div className="c-table-wrap"><table className="c-table"><thead><tr><th>Check / object</th><th>Identity</th><th>Expected → observed</th><th>Result</th></tr></thead><tbody>{proof.checks.map((c, i) => <tr key={i}><td><strong>{c.check.replaceAll("_", " ")}</strong><small>{c.artifact_id ?? "Verification route"}</small></td><td>{c.identity ?? "—"}</td><td>{c.expected ? `${c.expected} → ${c.observed}` : c.observed ?? "Readback comparison"}</td><td><span className={c.observed === "unknown" ? "c-neutral" : c.passed ? "c-positive" : "c-negative"}>{c.observed === "unknown" ? "Unknown" : c.passed ? "Passed" : "Failed"}</span></td></tr>)}<tr><td><strong>Alex’s unrelated positive control</strong><small>{context?.after?.artifact_id ?? "Pending"}</small></td><td>alex</td><td>allow → {context?.after ? context.after.result.allowed ? "allow" : "deny" : "unknown"}</td><td className={context?.after?.result.allowed ? "c-positive" : "c-neutral"}>{context?.after ? context.after.result.allowed ? "Passed" : "Failed" : "Unknown"}</td></tr></tbody></table></div><details className="c-hash"><summary>Inspect local record hash</summary><code>{proof.hash}</code><p>This can be compared with a trusted copy. It is not a signed third-party attestation.</p></details></article>;
}
